import React from 'react'
import { Link } from "react-router-dom";

const AddData = () => {
    // const navigate = useNavigate();
    return (
        <>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div> <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div> <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div> <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div> <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <div>AddData</div>
            <Link to="/readData">
                Click me</Link>
        </>

    )
}

export default AddData