import React from 'react'

export const ReadData = () => {
    return (
        <>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>
            <div>ReadData</div>

            <button>Click me</button>
        </>
    )
}
